### ISSUE TITLE
python ctrl+c does not throw KeyboardInterrupt

### ISSUE THREAD

**Issue by timmyichen** [replit/prybar#4]
Reproduction: Try ctrl+c-ing at this repl: https://repl.it/@xMikee/FBZ-Encoding

More details: https://replit.canny.io/bug-reports/p/python-ctrlc-does-not-produce-keyboardinterrupt-exception

**Comment by xMikee1** [comment]
Bug reporter here. Interesting to note: if I, from the Python interpreter in the browser, use `os.system('main.py')` to run the main.py file, `KeyboardInterrupt`s work perfectly fine. But when running the repl via the "run" button at the top of the page, the issue occurs.

**Comment by basicer** [comment]
Fixed in #6
